# Generated by Django 4.0.4 on 2022-05-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_remove_apply_checkbox_remove_apply_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='checkbox',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='name',
            field=models.TextField(),
        ),
    ]
