# Generated by Django 4.0.4 on 2022-05-30 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_alter_apply_checkbox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='checkbox',
            new_name='checkbox_1',
        ),
        migrations.AddField(
            model_name='apply',
            name='checkbox_2',
            field=models.TextField(null=True),
        ),
    ]
