# Generated by Django 4.0.4 on 2022-05-30 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_rename_checkbox_apply_checkbox_1_apply_checkbox_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='checkbox_2',
            new_name='PIagree',
        ),
        migrations.RenameField(
            model_name='apply',
            old_name='checkbox_1',
            new_name='koreandance',
        ),
    ]
