# Generated by Django 4.0.4 on 2022-06-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_contact_delete_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phonenumber_2',
            new_name='contact',
        ),
    ]
