# Generated by Django 4.0.4 on 2022-06-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_apply_how_think'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='how_think',
            field=models.CharField(choices=[('푸릇푸릇한 자연을 좋아해서.', '푸릇푸릇한 자연을 좋아해서.'), ('푸릇푸릇한 자연을 좋아해서.', '아무런 이유없이도 산책을 즐겨해요.'), ('생각(고민)의 정리가 필요할 때.', '생각(고민)의 정리가 필요할 때.'), ('스트레스를 해소하기 위해서.', '스트레스를 해소하기 위해서.')], max_length=30, null=True),
        ),
    ]
