# Generated by Django 4.0.4 on 2022-06-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0012_alter_apply_how_think'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='fruit',
            field=models.CharField(choices=[('apple', 'apple'), ('orange', 'orange'), ('grape', 'grape'), ('melon', 'melon')], max_length=10, null=True),
        ),
    ]
