# Generated by Django 4.0.4 on 2022-06-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0016_select_select_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='select',
            name='select_2',
            field=models.CharField(choices=[('바람', '바람'), ('보라연기', '보라연기'), ('내적댄스', '내적댄스'), ('온전한 것들', '온전한 것들'), ('서로의 존재 그리고 위로', '서로의 존재 그리고 위로')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='select',
            name='select_3',
            field=models.CharField(choices=[('바람', '바람'), ('보라연기', '보라연기'), ('내적댄스', '내적댄스'), ('온전한 것들', '온전한 것들'), ('서로의 존재 그리고 위로', '서로의 존재 그리고 위로')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='select',
            name='select_4',
            field=models.CharField(choices=[('바람', '바람'), ('보라연기', '보라연기'), ('내적댄스', '내적댄스'), ('온전한 것들', '온전한 것들'), ('서로의 존재 그리고 위로', '서로의 존재 그리고 위로')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='select',
            name='select_5',
            field=models.CharField(choices=[('바람', '바람'), ('보라연기', '보라연기'), ('내적댄스', '내적댄스'), ('온전한 것들', '온전한 것들'), ('서로의 존재 그리고 위로', '서로의 존재 그리고 위로')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='select',
            name='select_1',
            field=models.CharField(choices=[('바람', '바람'), ('보라연기', '보라연기'), ('내적댄스', '내적댄스'), ('온전한 것들', '온전한 것들'), ('서로의 존재 그리고 위로', '서로의 존재 그리고 위로')], max_length=20, null=True),
        ),
    ]
